### ISSUE TITLE
カメラが使えない・許可されていないときにメッセージを出して、使えないことがわかるようにする

### ISSUE THREAD

**Issue by ohakutsu** [geum-ztmy/zutomayo_OCR#1]
カメラが使えない・許可されていないときに、カメラ認識機能が使えないことをわかるようにしてほしいです！

過去にカメラをブロックしたことを忘れ、以下のスクリーンショットのように何も映らず、カメラ機能を使えず悩むことがありました。そのため、カメラが使えない場合は使えないことがわかると良いなと思いました！
（環境: Android 13. Chrome 115）

![screenshot](https://github.com/geum-ztmy/zutomayo_OCR/assets/39073321/691c901e-b0af-47a2-bce1-d385f252117d)

**Comment by ohakutsu** [comment]
Pull Requestを送ろうと思ったのですが、ライセンスが表記されておらずIssueにしました！
可能であれば、ライセンスを表記してもらえると嬉しいです！

**Comment by geum-ztmy** [comment]
ありがとうございます！
ライセンス表記は一応しておきました(?)
(無知すぎて間違ってるところがあるかもしれませんが..)
カメラが使用できない際にその旨を表示する機能は近日(数日以内に)追加しようと思います！

**Comment by ohakutsu** [comment]
@geum-ztmy 
ありがとうございます！

ライセンス表記していただいたので、Pull Requestを出してみました！
https://github.com/geum-ztmy/zutomayo_OCR/pull/2

もし、合わなければ修正もしくはクローズしていただいて大丈夫です！
